### ISSUE TITLE
Pipeline with SILVA taking long time?

### ISSUE THREAD

**Issue by sekhwal** [MaestSi/MetONTIIME#10]
Hi,
I am classifying my data with SILVA since I need classification of Archaea. Therefore, I RUN pipeline one day ago and it is still running. Is there any estimated time that it would take to produce results. Here, are the files and their size in my working directory...
It seems, it may take couple weeks to produce result which may not feasible..

-------------
Number of reads assigned to BC01: 18
Number of reads assigned to BC02: 11
Number of reads assigned to BC03: 39
Number of reads assigned to BC04: 25
Number of reads assigned to BC05: 13
Number of reads assigned to BC06: 33
Number of reads assigned to BC07: 4
Number of reads assigned to BC08: 26043
Number of reads assigned to BC09: 23447
Number of reads assigned to BC10: 26536
Number of reads assigned to BC11: 27
Number of reads assigned to BC12: 62

Compressing BC01.fastq file
Compressing BC02.fastq file
Compressing BC03.fastq file
Compressing BC04.fastq file
Compressing BC05.fastq file
Compressing BC06.fastq file
Compressing BC07.fastq file
Compressing BC08.fastq file
Compressing BC09.fastq file
Compressing BC10.fastq file
Compressing BC11.fastq file
Compressing BC12.fastq file

Running the MetONTIIME pipeline

Imported /home/kumarm/MinION-data/MetONTIIME/fast5_pass_analysis/analysis/manifest.txt as SingleEndFastqManifestPhred33V2 to sequences.qza
Saved FeatureTable[Frequency] to: table_tmp.qza
Saved FeatureData[Sequence] to: rep-seqs_tmp.qza
Saved FeatureTable[Frequency] to: table.qza
Saved FeatureData[Sequence] to: rep-seqs.qza
Saved Visualization to: demux_summary.qzv
Saved Visualization to: table.qzv
Saved Visualization to: rep-seqs.qzv
![Picture1](https://user-images.githubusercontent.com/26156590/72627400-4bf02000-3901-11ea-8f05-cb4ded0de38f.png)

**Comment by MaestSi** [comment]
Hi,
I don't have any precise estimate for running time. However, if you have a look at [Figure 5](https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0470-z/figures/5) by Bokulich et al., it seems that running time for Blast+ should scale linearly with the number of query sequences and the number of reference sequences, namely the size of the database. Since the number of query sequences you are classifying is the same as before, you can have a look at the number of reference sequences in the databases. In particular,
`cat PRJNA33175_Bacterial_16S.fasta | grep "^>" | wc -l`
results in about 20k sequences, while
` cat SILVA_132_QIIME_release/rep_set/rep_set_16S_only/99/silva_132_99_16S.fna | grep "^>" | wc -l`
results in about 370k sequences.
Therefore, classification of the same amount of reads with Silva db clustered at 99% identity is expected to take about 20 times the time required with NCBI 16S database. Two possible alternatives may be either reducing the number of query sequences by subsampling them (see config file for starting subsampling analysis from fast5 or just use seqtk to subsample reads from fastq.gz files) or to use a "compressed" version of silva database. For example, silva db clustered at 97% identity has about 170k sequences, clustered at 94% identity about 83k and clustered at 90% identity about 34k sequences.
Hope this helps,
Simone

**Comment by sekhwal** [comment]
Yes! it is helpful. It is good if I use 90% identity SILVA database. 
However, it is not clear for me how to subsampling query sequences either from fast5 or seqtk. Can you please elaborate the steps of how to do subsampling query sequences..

**Comment by MaestSi** [comment]
For example, if you want to subsample 1000 reads for each sample, you can use the following:
```
num_reads=1000
source activate MetONTIIME_env
mkdir "subsampling_"$num_reads"_reads"
for f in $(find . | grep "\\.fastq.gz" | grep -v subsampled); do
  seqtk sample $f $num_reads | gzip > "subsampling_"$num_reads"_reads/"$(basename $f)
done
```
While, if you want to subsample a portion of your reads starting from fast5, just set:
```
#if do_subsampling_flag <- 1, subsampling of num_fast5_files fast5 files is performed; otherwise set do_subsampling_flag <- 0
do_subsampling_flag <- 1
#num_fast5_files is the number of fast5 files to be subsampled/analysed (if do_subsampling_flag <- 1)                          
num_fast5_files <- 25
```
in the config file. As an example. these settings will subsample 25 fast5, each containing a number of reads set by the user when starting the MinKNOW (for instance 1 fast5 may contain 4000 reads). Clearly, since the fast5 subsampling is performed prior to demultiplexing, this will result in a different number of reads assigned to each sample.
Simone

**Comment by sekhwal** [comment]
Hi, I got my result by using 90% identity SILVA database. However, I can not see any Archaeal classifications this time also. I got all classification of Bacteria. Is there any way to get Archaeal classifications with SILVA by using the pipeline.
Thank you,

**Comment by MaestSi** [comment]
Hi, if the pipeline was able to detect any, you would have found them doing what you did. Silva clustered at 90% identity still has ~1800 16S Archaeal sequences. Are you sure they should be there, and moreover, they should be amplified using the primer set included in the SQK-RAB204 kit (27F and 1492R)? From what I read doing a quick Google search, the 27F primer might anneal to a Bacteria-specific domain.
Simone
