### ISSUE TITLE
CollapseTables only makes level 1 with greengenes DB

### ISSUE THREAD

**Issue by irc47** [MaestSi/MetONTIIME#105]
Hi Simone, 
I'm having a problem that I have seen described but not solved in previous issues. I'm using the greengenes database, so importDb is false and almost everything is going well, but diversity analysis fails and the collapse tables output has only level 1. If I set the diverstiy analysis to use level 1 then it runs, so I'm quite convinced that it is at the collapse tables step. 

The previous issues I saw solved this by using the NCBI database, but didn't seem to solve it with other databases. 

Here is my config file and the error. 
[diversity_analysis_error_july17.txt](https://github.com/user-attachments/files/16272197/diversity_analysis_error_july17.txt)
[metontiime2_NP22_greengenes.txt](https://github.com/user-attachments/files/16272198/metontiime2_NP22_greengenes.txt)

Thanks for your help!
-Ilana

**Comment by MaestSi** [comment]
Hi, I think in this case the issue may be due to the fact that, since you already have the qza file for taxonomy, you did not need to create it starting from the tsv, which you actually are not using/do not have. However, I just realised the tsv file is used for determining the number of taxonomic levels. Please unzip the qza file for the taxonomy artifact and, inside the data subfolder, you will find a tsv file. Please specify the path to that file as the the taxonomyTsv file in the config file. You do not need to rerun the taxonomyAssignment and related processes, but only the collapseTables and diversityAnalysis processes. Please let me know if this solves the issue.
Best,
SM

**Comment by irc47** [comment]
Wow, thank you for such a fast response. This solves it!
--Ilana
