### ISSUE TITLE
getting consensus sequence

### ISSUE THREAD

**Issue by ganiatgithub** [MaestSi/MetONTIIME#17]
Hi Simone,

Thanks for sharing this work.
I'm using MetONTIIME to process ONT data after 16S barcoding protocol.
For certain genera and species, I'm getting over 10k features, it was a lot to process. I left the MinION on for 36 hours as a trial, which is a long time.

Anyway, is there a way to get some consensus sequences from certain genera? I realize I was using `qiime feature-classifier classify-consensus-vsearch `for classification. But I'm not sure how to get consensus sequences from here.

The reason is that I wish to build phylogenetic trees using full length 16S genes, and the amount of features is just too much.

My command was:
```
./MetONTIIME.sh . ./sample-metadata.tsv /Users/uqgni1/Bioinfo-tools/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/99/silva_132_99_16S_sequence.qza /Users/uqgni1/Bioinfo-tools/SILVA_132_QIIME_release/taxonomy/16S_only/99/silva_132_99_16S_taxonomy.qza 6 VSEARCH 10 0.8 0.8
```

Kind regards,
Gaofeng

**Comment by MaestSi** [comment]
Hi Gaofeng,
if your main aim is to build a phylogenetic tree out of the features, you could try to use the **Evaluate_diversity.sh** script. That script performs clustering to reduce redundancy and to mitigate error rate and then builds a phylogenetic tree with clustered features. In fact, due to sequencing errors, it is meaningless to consider each amplicon sequence variant (ASV) as something informative, with a biological basis. Otherwise, you may be interested in trying to use a non phylogenetic diversity method (`qiime diversity core-metrics`) exploiting the feature table collapsed at a certain taxonomic level, e.g. genus level.
Does this answer your question?
Simone

**Comment by MaestSi** [comment]
Just a precisation: the feature classifier you used is called `classify-consensus-vsearch` because tuning the `MAX_ACCEPTS` parameter you are able to determine how many hits at maximum you are going to use for each read to perform a consensus taxonomy assignment, namely picking the taxonomy level at which >50% hits agree. In this case the term "consensus" is not related to consensus sequence, but to consensus taxonomy assignment.
Simone

**Comment by MaestSi** [comment]
Hi @ganiatgithub , I am going to close the issue, assuming your question was answered. If this is not the case, please repoen it.
Best,
Simone

**Comment by ganiatgithub** [comment]
Hi Simone,

Yes please close this now, I didn't manage to make too much progress on this yet, still trouble shooting.

Kind regards,
Gaofeng
