### ISSUE TITLE
Invalid value for '--input-path': Path

### ISSUE THREAD

**Issue by mishkb** [MaestSi/MetONTIIME#21]
Hi @MaestSi - I have had some success with using MetONTIIME now and thank you for this program!

My current issue is that I am getting an error as follows when I am trying to import the RefSeq database (BioProject 33175 fasta file) as you have in the README. 

(1/1) Invalid value for '--input-path': Path
  '/home/nano/BioProject_33175_RefSeqDB/sequence_accession_taxonomy.txt' does
  not exist.

The full terminal log for the session is attached.

I have been able to import the Silva_132_release database exactly as you have in the README - and successfully used **metontiime.sh** to analyse my fastq files that had already been basecalled by Guppy (& demultiplexed etc). Although I did end up with empty .tsv files in the collapsed_feature_tables folder? Could this me due to a too stringent <id thr> value? I was able to implement the Evaluate_diversity.sh script as well.

I think this error may be similar to that of [https://github.com/MaestSi/MetONTIIME/issues/14](url) - but when I tried adding gcc_linux-64 to the **Import_database.sh** I got the same error.

[MetONTIIME_error_NCBI_taxomony.txt](https://github.com/MaestSi/MetONTIIME/files/5606173/MetONTIIME_error_NCBI_taxomony.txt)

Can you shed any light on what I might be able to change/try?

-Michelle

**Comment by MaestSi** [comment]
Hi Michelle,
I confirm that the line `conda create -n entrez_qiime_env python=2.7 gcc` in **Import_database.sh** script was not working anymore, as already described in Issue #14.  In fact, I removed the `entrez_qiime_env` environment and tried to reproduce your issue, and when using the line with `gcc` I got the same error message as yours. However, when changing `gcc` to `gcc_linux-64`, it successfully created the environment and imported the database. Could you please provide me with the error message that you get when using `gcc_linux-64`? Moreover, I would suggest to `conda deactivate MetONTIIME_env` before running **Import_database.sh**. In fact I noticed that if conda doesn't find gcc (although [it should)](https://anaconda.org/conda-forge/gcc), the environment entrez_qiime_env (which is based on python2) is not going to be created at all, and the script is going to fail because it is trying to use the python version found in the current environment (which is python3), producing syntax errors.
Simone

**Comment by mishkb** [comment]
Thanks Simone for your quick response. I've deactivated the `MetONTIIME_env` and changed to `gcc_linux-64` in **Import_database.sh**. Running the script again now and will see in an hour or so how it goes. 

-Michelle

**Comment by mishkb** [comment]
Fantastic! - With your instructions @MaestSi the import worked. As I said above, I deactivated the METONTIIME_env, and changed to gcc_linux-64 and got no errors. And now have the required QIIME artifacts from the BioProject 33175 fasta file.

**Comment by MaestSi** [comment]
Glad it worked!
Cheers,
Simone

**Comment by GeybyTatiana** [comment]
Hello, I have the same problem, already change to gcc_linux-64, but the error continue, help please.

**Comment by MaestSi** [comment]
Hi, could you please report the output that you get when you run **Import_database.sh**?
Thanks,
Simone

**Comment by GeybyTatiana** [comment]
There was a problem with the command:
 (1/1) Invalid value for '--input-path': Path
  '/mnt/d/bioinform1/MetONTIIME/16sepi2me_accession_taxonomy.txt' does not
  exist. 

and archives that i get were 16sepi2me_sequence.qza and 16sepi2me.txt

**Comment by MaestSi** [comment]
What I don't understand is why you get 16sepi2me.txt file (which should be generated by the following commands, please check) instead of 16sepi2me_accession_taxonomy.txt

```
source activate entrez_qiime_env
python ./entrez_qiime/entrez_qiime.py -i 16sepi2me.fasta -n ./taxonomy/taxdump -a ./taxonomy/nucl_merged.accession2taxid
```
Best,
Simone

**Comment by GeybyTatiana** [comment]
![image](https://user-images.githubusercontent.com/54871908/122657507-b1b18e80-d129-11eb-870d-f793e2b6ed1d.png)
![image](https://user-images.githubusercontent.com/54871908/122657516-c9891280-d129-11eb-9c1b-812c7e429a81.png)
![image](https://user-images.githubusercontent.com/54871908/122657526-e1609680-d129-11eb-9a92-fd3c07a68aae.png)
![image](https://user-images.githubusercontent.com/54871908/122657535-ede4ef00-d129-11eb-83d7-79e2aca954ea.png)

**Comment by MaestSi** [comment]
Hi,
the "Invalid value for '--input-path'" error is generated from:

```
qiime tools import \
--type FeatureData[Taxonomy] \
--input-format HeaderlessTSVTaxonomyFormat \
--input-path $TAXONOMY_TSV \
--output-path $TAXONOMY
```
but it is due to a previous command not working properly. That is why I asked if you could please run only:
 
```
source activate entrez_qiime_env
python ./entrez_qiime/entrez_qiime.py -i 16sepi2me.fasta -n ./taxonomy/taxdump -a ./taxonomy/nucl_merged.accession2taxid
```
In fact, I need to know why file 16sepi2me_accession_taxonomy.txt is not generated by the latter command.
Thanks,
Simone

**Comment by GeybyTatiana** [comment]
This is my results..

![image](https://user-images.githubusercontent.com/54871908/122680963-90977f00-d1b7-11eb-87b1-614cac250ab9.png)

**Comment by MaestSi** [comment]
Hi, I see that you are running the command as super user (sudoer), did you also run the full script like that? Otherwise you may be using a different python version. Is it necessary to run it as super user?
