### ISSUE TITLE
MetonTIIME

### ISSUE THREAD

**Issue by kak8** [MaestSi/MetONTIIME#25]
Hello.
I am trying to analyze nanopore data on MetONTIIME.
However, the analysis stopped after sequences.qza file was generated.
Hello. The analysis stopped after I got sequences.qza file.
How do I proceed now? I was under the notion that we would be getting feature table and taxonomy table as well. Should I proceed with the conventional QIIME2 pipeline after this step or is there some error that I might be facing?
Also, the nohup.out file is blank.
Kindly guide me.
Thank you

**Comment by MaestSi** [comment]
You may have an empty nohup.out file if you forgot to put ‘&’ at the end of the command.
First, I would advise to remove all generated files with extension .qz*. Then I would be sure nothing is still running (with `htop -u <username>` command, for example) and rerun the pipeline. If it stops again, please post here the content of the nohup.out file.
Simone

**Comment by kak8** [comment]
Hello
I didn’t forget to put & after my command.
Also the only file that has got generated is sequences.qza
Should I delete that file?
Ididnt understand this-Then I would be sure nothing is still running (with htop -u <username> command, for example) 
It would be really nice if you could elaborate.
Thank you

**Comment by MaestSi** [comment]
I was saying that because also a message reporting the successful import of sequences.qza file should have been created there. Yes, delete the sequences.qza file and run again the pipeline.
If you are running on Ubuntu (as is probably the case) you could use the `htop` command (let's say your user id is mim you could run `htop -u mim`) and see if there are any jobs running (and in case, kill them). In fact, the MetONTIIME pipeline runs in background and you have no other way to check its progress a part from looking at the nohup.out file and monitoring what is running with htop.

**Comment by kak8** [comment]
nohup out- Imported /home/mim/MetONTIIME/files/manifest.txt as SingleEndFastqManifestPhred33V2 to sequences.qza.
No other process is running in the background.
Kindly suggest.

**Comment by MaestSi** [comment]
After your fastq.gz files are imported either the analysis is continuing (a tool called Vsearch should be running) or you should get an error message in the nohup.out file. It seems strange to me that you don't have any errors and the analysis is not running anymore.
Simone

**Comment by kak8** [comment]
As rightly suggested by you, I stopped all the processes.
I have got the following files-
rep-seqs_tmp.qza
table_tmp.qza
The analysis stopped after this.
(MetONTIIME_env) mim@mim-SVR-TS700-E9-RS8:~/MetONTIIME$ nohup ./MetONTIIME.sh /home/mim/MetONTIIME/files /home/mim/MetONTIIME/covidmetadata.tsv /home/mim/MetONTIIME/silva_132_99_16S_sequence.qza /home/mim/MetONTIIME/silva_132_99_16S_taxonomy.qza 4 Vsearch 3 0.8 0.85 &
[3] 9619
(MetONTIIME_env) mim@mim-SVR-TS700-E9-RS8:~/MetONTIIME$ nohup: ignoring input and appending output to 'nohup.out'
(MetONTIIME_env) mim@mim-SVR-TS700-E9-RS8:~/MetONTIIME$ 
Is it ok?

**Comment by MaestSi** [comment]
Once you are sure no process of the pipeline is running, remove all .qza and .qzv files and rerun the pipeline. How can you say that the analysis stopped? Did you find any error message? If the answer is no, it may be still running.
Simone

**Comment by kak8** [comment]
I felt the analysis stopped because the command executed for sometime and then- 
(MetONTIIME_env) mim@mim-SVR-TS700-E9-RS8:~/MetONTIIME$(which I assumed will appear once the command  which is actively running is executed as the cursor was not flashing.  So it meas, that even if the command is completed on the terminaI, it might still be running? I  will try again as you have suggested.
I am sorry, if  I have been asking basic doubts, but I am running this program for the first time.
I really thank you for your quick and timely response

**Comment by MaestSi** [comment]
There are 2 options:
- Run `nohup <command> &`
- Run `<command>`

In the first case (suggested) the program will run in background. You will be able to close the shell with no effect, the program will still be running, and you will find the logs in the nohup.out file.
In the second case, the program will be running in foreground, and the cursor will start flashing once the analysis is complete. However, in case you quit the shell, the program will stop. Since the analysis may take hours/days I don't encourage this way of running the program.
Simone

**Comment by MaestSi** [comment]
Hi @kak8 , were you finally able to run the pipeline without errors, or are still there any issues?

**Comment by kak8** [comment]
Hello..Yes,I started the run..its running currently.I thought I would get
back when the analysis is complete.
But I thank you for your help.

**Comment by MaestSi** [comment]
Perfect, let me know if it completes succesfully, otherwise feel free to reopen the issue!
Simone
