### ISSUE TITLE
To start with fastq file

### ISSUE THREAD

**Issue by watayako** [MaestSi/MetONTIIME#42]
Dear Simone,

I want to ask for your help.
I've tried to run my data on your pipeline MetONTIIME, but unfortunately, I haven't succeeded yet. 

The latest error message that I got is followings: 

(MetONTIIME_env) ayako@DESKTOP-B54P3SI:~$ nohup ./MetONTIIME.sh /home/ayako/nanopore/FAP89498_pass_barcode01_a8865088_bigfile.fastq.gz  /home/ayako/nanopore/sample-metadata.txt  /home/ayako/nanopore/silva-138-99-seqs.qza  /home/ayako/nanopore/silva-138-99-tax.qza 5 Vsearch 3 0.8 0.85 &
[1] 5254
(MetONTIIME_env) ayako@DESKTOP-B54P3SI:~$ nohup: ignoring input and appending output to 'nohup.out'
nohup: failed to run command './MetONTIIME.sh': No such file or directory

So, could you walk me through how to analyze data starting from fastq files?
I installed MetONTIIME and activated it , and then what is the next step?

I appreciate your help.

Best regards,

Ayako

**Comment by MaestSi** [comment]
Hi,
based on this error:
`nohup: failed to run command './MetONTIIME.sh': No such file or directory`
it looks like you are not in the MetONTIIME directory. So, I think you should just cd to the directory where you downloaded the pipeline.
Best,
Simone

**Comment by watayako** [comment]
Dear Simone,

Thank you for the advice.
Followed by your instruction, I could solve the problems.

But, I got another trouble.
Phred quality score seems to be out of range.
I think the MetONTIIME applied SingleEndFastqManifestPhred33V2.
Have you met any similar troubles?

Find the attached file.

Best regards,

Ayako

![220118_MetONTIIIME](https://user-images.githubusercontent.com/97872382/149879530-d6e7f90d-67d1-4e9b-b885-bd87b7c4d011.png)

**Comment by MaestSi** [comment]
Hi,
the mean quality score looks like centered around 20, which may be a bit over-optimistic (that would correspond to a accuracy of 99%), but not absurd: with latest chemistries and base-callers you are expected to approach quite high accuracies. So, I don't think it is a matter of wrong PHRED offset, SingleEndFastqManifestPhred33V2 seems right to me. Based on the plot, it looks like the quality distribution has a lower variance for coordinates 1 to 1600 compared to the remaining part of the plot, is 1600 bp the expected amplicons? Quality values at higher coordinates seem to be due to a lower number of reads, thus the higher variance. If this is the case, I suggest you to apply more stringent quality filtering, in order to discard non-specific amplification products. Moreover, I suggest you to check quality plots produced by pycoQC in the qc folder.
Best,
Simone

**Comment by MaestSi** [comment]
Hi, I am closing the issue due to inactivity. Feel free to reopen it, in case you have any other related issues.
Simone

**Comment by watayako** [comment]
Sorry for the long silence.

I have not tried your advice yet, so I will post an issue when I get a problem.

Thanks a lot.

Ayako
