### ISSUE TITLE
Preparation of FASTQ

### ISSUE THREAD

**Issue by ysuzuki1978** [MaestSi/MetONTIIME#59]
I would like to analyze the FASTQ output using my own guppybasecaller GPU instead of the MetONTIIME pipeline.
Is it necessary to pre-process the reads with Nanofilt (e.g. remove reads less than 500 bp or longer than 2 Kbp) and sample them to 100 K reads with seqtk before running MetONTIIME.sh?

Best,

**Comment by MaestSi** [comment]
Hi,
if you want to start the analysis from fastq.gz files, yes. Otherwise, if your fast5 reads are in <fast5_dir> folder, you can create <fast5_dir>_analysis/basecalling folder, and put the fastq files produced by Guppy into the basecalling folder (prior to demultiplexing; if they have already been demultiplexed, be sure they still contain the indexes). Then, you can start the pipeline with Launch_MinION_mobile_lab.sh script. In case the basecalling folder is found, basecalling will be skipped and demultiplexing + reads filtering will be performed.
SM

**Comment by ysuzuki1978** [comment]
We are using this paper as a reference for our 16S analysis.
https://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-021-02094-5

I used the 4Primer method and trimmed 45bp from the barcode and the primer part.
 I also extracted only the 1300-1950bp reads.

For detailed bacterial flora analysis, we are sampling about 80k reads for further analysis.

Can I use fewer reads for downstream analysis diversity analysis?

YS

**Comment by MaestSi** [comment]
The number of reads you should use for downstream analysis strongly depends on the richness of your samples, and the taxonomy level at which you want to perform your analyses. I strongly suggest producing some alpha rarefaction curves at different taxonomy levels, to check whether you reached a plateau in alpha diversity with fewer reads or not. 
SM

**Comment by MaestSi** [comment]
Hi, I'm closing the issue. Feel free to reopen it if you have any further related questions.
SM
