### ISSUE TITLE
ERROR ~ Error executing process > 'concatenateFastq'

### ISSUE THREAD

**Issue by hvanderheyden** [MaestSi/MetONTIIME#62]
Hello There, 
I am trying your MetONTIIME pipeline with nanopore ITS amplicon sequencing 
As a starter I tried with a very small data set having only 5 fastq.gz files already concatenated
However I keep having an error message for concatenateFastq.
Please see the log file attached 
Many thanks for sharing the pipeline 
Cheers
RV

**Comment by MaestSi** [comment]
Hi,
I think you forgot to attach the log file.
Best,
SM

**Comment by hvanderheyden** [comment]
Hello and thank you for your answer 

here are the code lines: nextflow \
-c metontiime2.conf run metontiime2.nf \
--workDir=/media/herve/10TB/Apogee/MetONTIIME/WD \
--resultsDir=/media/herve/10TB/Apogee/MetONTIIME/resultsDir \
-profile docker

and the log and conf file 

[nextflow.txt](https://github.com/MaestSi/MetONTIIME/files/11937436/nextflow.txt)
[metontiime2.conf.txt](https://github.com/MaestSi/MetONTIIME/files/11937498/metontiime2.conf.txt)

In the the workDir, I have 5 fastq.gz files already concatenated 1 fastq.gz file = 1 run

**Comment by MaestSi** [comment]
Hi,
first I think you should also mount /media directory, in order to make it accessible to docker (by default, only /home is accessible).
You could do that editing config file at line 173:
`containerOptions = '-v /home/:/home -v /media:/media'`
If you did demultiplexing (live with MinKNOW or with guppy_barcoder), and in workDir you have folders named "barcode\<XX\>", with each folder containing a set of fastq files for each sample, then **concatenateFastq** should be set to true (line 50 of **metontiime2.conf**). While, if in the workDir you already have demultiplexed fastq.gz file, with each file corresponding to a sample, **concatenateFastq** process should be set to false. Lastly, if you haven't done demultiplexing yet (as it seems from your sentence (1 fastq.gz file = 1 run)), please do it with Guppy, and then run MetONTIIME pipeline afterwards (setting **concatenateFastq** process to true or to false accordingly).
SM

**Comment by MaestSi** [comment]
Hi, I just corrected a bug causing diversityAnalysis process to start before collapseTables process was completed. Please download the updated metontiime2.nf script before re-running the pipeline.
SM

**Comment by MaestSi** [comment]
Hi, are there any updates on this issue?
Best,
SM

**Comment by hvanderheyden** [comment]
Hello Simone, 
yes, I managed to have your pipeline to run with my mock samples. 
Thank you for your help. 
I am not sure however that Qiime2 is working well for my datasets. 
In the next few days, I will play with the parameters and see how it goes. 
If you want I can share some results with, perhaps via email. 
Cheers 
RV

**Comment by MaestSi** [comment]
Yes, I'd be happy to have a look at them, if you want.
Best,
SM

**Comment by MaestSi** [comment]
Hi, I am going to close the issue.
In case you have any further questions, feel free to reopen it.
Best,
SM
