### ISSUE TITLE
Question: filtering features for nanopore sequencing data

### ISSUE THREAD

**Issue by tjlim10** [MaestSi/MetONTIIME#88]
Hi Simone,

I hope you are well. May I know for MetONTIIME, is there any form of filtering, either _p-min-samples_ or _p-min-frequency_ ? As I think filtering of the rare features is usually done in QIIME2 to minimise sequencing errors. I would expect nanopore sequencing to have more errors than illumina/MGI sequencing, so have you ever came across working with this? I tried to set _--p-min-samples 2_ and _--p-min-frequency 10_, unfortunately they filtered out too many features.

Thanks!

Kind regards,
Timothy

**Comment by MaestSi** [comment]
Hi Timothy,
what I usually do (implemented in MetONTIIME2 in the `filterTaxa` process) is to filter the feature table based on taxa of interest (`qiime taxa filter-table` command) and only then filter the resulting table based on min frequency (`qiime feature-table filter-samples` command). However, the threshold you should set is highly dependent on the specific project (sequencing depth, expected abundance of the target taxa, ...). As an alternative, you may reduce the impact of sequencing errors by focusing on higher-level taxonomy (e.g. genus-level instead of species-level). I hope this helps.
SM

**Comment by tjlim10** [comment]
Hi Simone,

I see, thanks a lot for the input!

Kind regards,
Timothy
